### ISSUE TITLE
Passing ClientToServer and ServerToClients types to socket instance?

### ISSUE THREAD

**Issue by talkingdonkeyz** [nitedani/socket.io-react-hooks#17]
Is it possible to pass types to the socket as you would when not using a hook?

**Comment by nitedani** [comment]
Added support for this in 1.0.16.
I'll fix the interface order in v2.

interface ServerToClientEvents {
  noArg: () => void;
  basicEmit: (a: number, b: string, c: any) => void;
  withAck: (d: string, callback: (e: number) => void) => void;
}

interface ClientToServerEvents {
  hello: () => void;
}

const { socket } = useSocket<
  {},
  Socket<ServerToClientEvents, ClientToServerEvents>
>();

**Comment by talkingdonkeyz** [comment]
That makes sense. Thanks!!
